[theme]
primaryColor = "#f63366"
# backgroundColor = "white"
backgroundColor = "white"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#393939"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true
